services:
  postgres:
    image: postgres:latest
    container_name: nourishhub-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nourishhub_auth_db

    ports:
      - "5432:5432"